sudo: required
services:
  - docker

before_install:
  cd project
  - docker build -t jessietabilisma/kaagapAI -f Dockerfile.dev .

script:
  - docker - docker run jessietabilisma/kaagapAI npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "kaagapAI"
  env: "Kaagapai-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-647912191476"
  bucket_path: "kaagapAI"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
